### ISSUE TITLE
problems with demo

### ISSUE THREAD

**Issue by MC-E** [Abdul-Mukit/robust_hand_tracking#1]
Hi , I operate demo.py but it does not detect hands then I operate demo_realsense_gamma_analysis.py there is something wrong with it :
D:\Anaconda2\anaconda2\envs\py3\python.exe D:/pc/robust_hand_tracking-master/demo_realsense_gamma_analysis.py
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   13 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   14 conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
   15 detection
Loading weights from 000570.weights... Done!
Traceback (most recent call last):
  File "D:/pc/robust_hand_tracking-master/demo_realsense_gamma_analysis.py", line 88, in <module>
    demo(cfgfile, weightfile)
  File "D:/pc/robust_hand_tracking-master/demo_realsense_gamma_analysis.py", line 39, in demo
    profile = pipeline.start(config)
RuntimeError: No device connected
I do not know what happened. Looking forward to your reply.
Thanks!

**Comment by Abdul-Mukit** [comment]
RuntimeError: No device connected
means that your computer can't detect the IntelRealsense camera. Check that if your intel realsense camera is connected properly.
I used the Intel realsense D435i camera for this.

**Comment by Abdul-Mukit** [comment]
By the way, what was the error message when you ran "demo.py"?

**Comment by MC-E** [comment]
Thank you,I use wrong version of realsense(R200) which does not support pyrealsense2.
There is no error with demo.py beacuse it does not use realsense camera but it can not detect hands,output '---------' constantly.I use the checkpoint(000570.weight) that you provide.Did I use the wrong weight?

**Comment by Abdul-Mukit** [comment]
Thank you very much for pointing this out. I probably uploaded the wrong weight. There was a big gap between the time I did this project and when I uploaded the project on github. Probably I mixed up the weights. I'll upload the correct weight or fix the problem asap.

**Comment by Abdul-Mukit** [comment]
I uploaded the correct weight. Can you please check?

**Comment by MC-E** [comment]
Thank you very much,it is ok!Now the model can detect hands perfectly.

**Comment by MC-E** [comment]
Hi,did you remember how many epochs to train to get this weights?I am training in yolov3 but the result is worse than yours.

**Comment by Abdul-Mukit** [comment]
Sorry, I don't remember. Did you eventually get the results you were hoping for?
